config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/" => "home#index"

  resources :todos

  resources :users
  post "users/login", to: "users#validate"

  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :todo_text, presence: true
  validates :todo_text, length: { minimum: 2 }
  validates :due_date, presence: true

  belongs_to :user

  def to_pleasant_string
    is_completed = completed ? "[X]" : "[ ]"
    "#{id} #{due_date.to_s(:long)} #{todo_text} #{is_completed}"
  end

  def due_today?
    due_date == Date.today
  end

  def overdue?
    due_date < Date.today
  end

  def due_later?
    due_date > Date.today
  end

  def self.of_user(user)
    all.where(user_id: user.id)
  end

  def self.overdue
    all.where("due_date < ? and completed = ?", Date.today, false)
  end

  def self.due_today
    all.where("due_date = ?", Date.today)
  end

  def self.due_later
    all.where("due_date > ?", Date.today)
  end

  def self.add_task(todo)
    create!(todo_text: todo[:todo_text], due_date: Date.today + todo[:due_in_days], completed: false)
  end

  def self.show_list
    puts "My Todo-list\n"
    puts "\n"
    puts "Overdue\n"
    puts overdue.map { |todo| todo.to_displayable_string }
    puts "\n\n"
    puts "Due Today\n"
    puts due_today.map { |todo| todo.to_displayable_string }
    puts "\n\n"
    puts "Due Later\n"
    puts due_later.map { |todo| todo.to_displayable_string }
  end

  def to_displayable_string
    display_status = completed ? "[X]" : "[ ]"
    display_date = due_today? ? nil : due_date
    "#{id} #{display_status} #{todo_text} #{display_date}"
  end

  def self.mark_as_complete!(todo_id)
    todo = Todo.find(todo_id)
    todo.completed = true
    todo.save
    todo
  end

  def self.completed
    all.where(completed: true)
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :email, presence: true
  validates :password, presence: true

  has_secure_password
  has_many :todos

  def to_pleasant_string
    "#{id} #{first_name} #{email}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      redirect_to "/"
    end
  end

  def current_user
    return @current_user if @current_user

    current_user_id = session[:current_user_id]
    if current_user_id
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    if current_user
      redirect_to todos_path
    else
      render "index"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user and user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to "/"
    else
      flash[:error] = "Your Login attempt was invalid.Please Retry"
      redirect_to new_sessions_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    redirect_to "/"
  end
end

app/controllers/todos_controller.rb
# todos_controller.rb
class TodosController < ApplicationController
  def index
    @todo = current_user.todos
    render "index"
  end

  def show
    id = params[:id]
    todo = Todo.of_user(current_user).find(id)
    render "todo"
  end

  def create
    todo_text = params[:todo_text]
    due_date = params[:due_date]
    new_todo = Todo.new(
      todo_text: todo_text,
      due_date: due_date,
      completed: false,
      user_id: current_user.id,
    )
    if new_todo.save
      redirect_to todos_path
    else
      flash[:error] = new_todo.errors.full_messages.join(", ")
      redirect_to todos_path
    end
  end

  def update
    id = params[:id]
    completed = params[:completed]
    todo = current_user.todos.find(id)
    todo.completed = completed
    todo.save!
    redirect_to todos_path
  end

  def destroy
    id = params[:id]
    todo = current_user.todos.find(id)
    todo.destroy
    redirect_to todos_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    render plain: User.order(:id).map { |user| user.to_pleasant_string }.join("\n")
  end

  def show
    id = params[:id]
    user = User.find(id)
    render plain: user.to_pleasant_string
  end

  def create
    user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      password: params[:password],
    )
    if user.save
      session[:current_user_id] = user.id
      flash[:success] = "Signed-up Successfully!!"
      redirect_to todos_path
    else
      flash[:error] = user.errors.full_messages.join(", ")
      redirect_to new_user_path
    end
  end

  def validate
    check_user = User.where("email=? and password =?", params[:email], params[:password]).exists?
    render plain: check_user
  end

  def new
    render "users/new"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1 class="Home-title">Welcome to the Todo homepage</p>

<h3 class="Home-authenticate">If you are a new user,<%= link_to "Sign-up here", new_user_path%></p>
<h3 class="Home-authenticate">If you are an existing user, <%=link_to "Sign-in here",new_sessions_path%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if @current_user%>
      <p class="UserHeader">
        Welcome <%=@current_user.first_name%>!
        <%=link_to "Sign-out",destroy_session_path, method: "delete"%>
      </p>
    <% end %>
    <% if flash[:error] %>
      <p class="Flash-error"> <%= flash[:error] %> </p>
    <% end %>
    <% if flash[:success] %>
      <p class="Flash-success"> <%= flash[:success] %> </p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/todos/_todo-section.html.erb
<section class="TodoSection">
  <div class="TodoSectionTitle">
    <h2 class="TodoSection-title"><%= section_title %></h2>
    <p class="Completed-Label"><%= todos.completed.count %>/<%= todos.count %></p>
  </div>
  <ul>
    <% todos.each do |todo| %>
        <li class="TodoItem">
          <div class="TodoItem-container">
            <%= form_with(url: "/todos/#{todo.id}" , method: "put") do %>
              <%= check_box_tag("completed",
                  value=nil,
                  checked=todo.completed,
                  {onclick: "this.form.submit()",
                  class: "TodoSection-checkbox"})
              %>
            <% end %>

            <%class_name = (todo.completed)? "Todo-Display-Completed": "Todo-Display"%>
            <p class=<%=class_name%>><%= todo.todo_text %></p>

            <% if show_due_date %>
              <p class="TodoItem-dueDate"><%= todo.due_date.to_s(:short) %> </p>
            <% end %>
            <a class="TodoItem-delete ">
              <%= form_with(url: "/todos/#{todo.id}" , method: "delete") do %>
                <%= image_submit_tag("trash.svg") %>
              <% end %>
            </a>
          </div>
        </li>
   <% end %>
  </ul>
</section>

app/views/todos/index.html.erb
<main class="TodoPageMain">
  <article>
    <%= content_tag(:h1 , class: "TodoPage-Title") do-%>
      My Todo-list
    <% end -%>
    <%= form_with(url: "/todos", method: "post", class: "TodoSectionTitle") do %>
      <%= text_field_tag 'todo_text', '' , autofocus: true,
                                          placeholder: "What's next",
                                          class: 'TodoSection-text'
      %>
      <%= date_field_tag('due_date',nil,class: "TodoSection-date") %>
      <%= button_tag("Add",type: "submit",class: "TodoSection-button") %>
    <% end %>

    <%= render partial: "todo-section", locals: {
      section_title:"Overdue",
      todos: @todo.overdue,
      show_due_date: true
      }  %>
    <%= render partial: "todo-section",locals:{
      section_title: "Due Today",
      todos: @todo.due_today,
      show_due_date: false
    } %>
    <%= render partial: "todo-section", locals:{
      section_title: "Due Later",
      todos: @todo.due_later,
      show_due_date: true
    } %>

  </article>
  </main>

app/views/users/new.html.erb
<p class="NewUsers-title">Welcome new user</p>

<section class = "UsersNew">
<%= form_with url: users_path do |form| %>
  <div class="Form-section">
    <p class="FormInput-label">First Name:</p>
    <%= form.text_field :first_name,
                        class: "Form-input",
                        autofocus: true
    %>
  </div>
  <div class="Form-section">
    <p class="FormInput-label">Last Name:</p>
    <%= form.text_field :last_name,
                        class: "Form-input" %>
  </div>
  <div class="Form-section">
    <p class="FormInput-label">Email:</p>
    <%= form.email_field :email, class: "Form-input"%>
  </div>
  <div class="Form-section">
    <p class="FormInput-label">Password:</p>
    <%= form.password_field :password,
                            class: "Form-input" %>
  </div>
  <div class="Form-section">
    <%= form.submit "Sign-up!", class: "Form-submit"%>
  </div>
<% end %>
</section>